highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


url: http://tapasweni-pathak.github.io/
baseurl: http://tapasweni-pathak.github.io/
title: Tapasweni Pathak
author: Tapasweni Pathak
description: Homepage of Tapasweni Pathak.
avatar: profile.png
email: tapaswenipathak@gmail.com
github: tapasweni-pathak # username
twitter: TapasweniPathak
linkedin: tapaswenipathak


# needed for travis-ci build
exclude: [vendor]
